server:
  port: 8080

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/security}
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
